version: '3'

services:
  limesurvey:
    image: edgarrmondragon/limesurvey
    build:
      context: ${LS_DOCKERFILE_CONTEXT:-https://github.com/martialblog/docker-limesurvey.git#master:6.0/apache}
      dockerfile: ${LS_DOCKERFILE:-Dockerfile}
      args:
        version: ${LS_VERSION}
        sha256_checksum: ${LS_CHECKSUM}
